spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jportal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
      show-sql: true
jwt:
  private.key: classpath:rsa_private_key.pem
  public.key: classpath:rsa_public_key.pem