spring:
  datasource:
    url: jdbc:mysql://119.91.142.170:3306/king_domain?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: biguser
    password: EP6P7nnk9ZsY916hGKET

  jpa:
    show-sql: true